### ISSUE TITLE
Suggestion: Snippets for Surfaces 

### ISSUE THREAD

**Issue by SterlingButters** [repositony/vscode_mcnp#11]
I'm guessing this is already planned but it would be nice to select surface types from a dropdown also

**Comment by repositony** [comment]
Excellent idea, this was overlooked for the snippets

**Comment by repositony** [comment]
Snippets for macrobodies added in commit 53561a7f9d05e19c92238ea45d9b84536c0021ef for v1.0.3. Will probably add surfaces in a simpler way as they generally have fewer parameters and can just be one-liners.
